apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.deployment.name }}