{{- range $name, $config := .Values.mongodb }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: mongodb-{{ $name }}
spec:
  serviceName: mongodb-{{ $name }}
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-{{ $name }}
  template:
    metadata:
      labels:
        app: mongodb-{{ $name }}
    spec:
      containers:
        - name: mongodb
          image: {{ $config.image }}
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ $config.database }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $config.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: mongodb-{{ $name }}
spec:
  clusterIP: None
  selector:
    app: mongodb-{{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
  type: ClusterIP
---
{{- end }}
