{{- range $name, $config := .Values.postgresql }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: postgresql-db-{{ $name }}
spec:
  serviceName: postgresql-db-{{ $name }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db-{{ $name }}
  template:
    metadata:
      labels:
        app: postgresql-db-{{ $name }}
    spec:
      containers:
        - name: postgresql
          image: {{ $config.image }}
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: POSTGRES_DB
              value: {{ $config.database }}
            - name: POSTGRES_USER
              value: {{ $config.username }}
            - name: POSTGRES_PASSWORD
              value: {{ $config.password }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $config.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: postgresql-db-{{ $name }}
spec:
  clusterIP: None
  selector:
    app: postgresql-db-{{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
  type: ClusterIP
---
{{- end }}
