apiVersion: v1
kind: Service
metadata:
  name: {{.Values.client.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.client.service.name}}
spec:
  type: {{.Values.client.service.type}}
  ports:
    - port: {{.Values.client.service.port}}
      protocol: TCP
      nodePort: {{.Values.client.service.nodePort}}
  selector:
    app: {{.Values.client.deployment.name}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.client.deployment.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.client.deployment.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{.Values.client.deployment.name}}
  template:
    metadata:
      labels:
        app: {{.Values.client.deployment.name}}
    spec:
      containers:
        - name: {{.Values.client.deployment.name}}
          image: "{{ .Values.client.deployment.image.repository }}:{{ .Values.client.deployment.image.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.client.deployment.containerPort}}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: VITE_USER_API_URL
              value: {{.Values.client.env.userApiUrl}}
            - name: VITE_ACCOMMODATIONS_API_URL
              value: {{.Values.client.env.accommodationApiUrl}}
            - name: VITE_RESERVATIONS_API_URL
              value: {{.Values.client.env.reservationApiUrl}}
            - name: VITE_RATING_API_URL
              value: {{.Values.client.env.ratingApiUrl}}
            - name: VITE_APP_NAME
              value: {{.Values.client.env.appName}}
            - name: VITE_STANDARD_FIELD_MAX_LENGTH
              value: "{{ .Values.client.env.standardFieldMaxLength }}"
            - name: VITE_LONGER_FIELD_MAX_LENGTH
              value: "{{ .Values.client.env.longerFieldMaxLength }}"
            - name: VITE_MAX_FILE_SIZE
              value: "{{ .Values.client.env.maxFileSize }}"
      # imagePullSecrets:
      #   - name: {{.Values.client.deployment.imagePullSecret}}
