{{- range $serviceName, $service := .Values }}
{{- if and (kindIs "map" $service) (hasKey $service "metrics") (get $service.metrics "enabled") }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $serviceName }}-servicemonitor
  labels:
    release: monitoring
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: {{ $service.deployment.name }}
      # app.kubernetes.io/managed-by: Helm
  # namespaceSelector:
  #   matchNames:
  #     # - {{ $.Values.namespace }}
  #     - monitoring
  namespaceSelector:
    matchNames:
      - booking
  endpoints:
    - port: http
      path: {{ $service.metrics.path }}
      interval: {{ $service.metrics.interval | default "15s" }}

{{- end }}
{{- end }}
